### ISSUE TITLE
Pola z nazwą i ceną krypto są czasem za długie a czasem przycięte

### ISSUE THREAD

**Issue by lilwando** [Mabi671/CryptoMarket#6]
<img width="603" alt="image" src="https://github.com/Mabi671/CryptoMarket/assets/95501673/5b5669b0-3f8d-4541-92eb-5a03949b4715">

Powinno być przyjęte jaką szerokość ma maksymalnie pole dla najdłuższej nazwy i ile bedzie zajmowac maks cena

**Comment by Mabi671** [comment]
Teraz wszystkie są za długie 🙃

**Comment by lilwando** [comment]
Potwierdzam, są za długie ale przynajmniej wszystkie się mieszczą
